# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeneratorService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16GeneratorService.proto\x12\x10\x63om.example.grpc\";\n\x10GeneratorRequest\x12\x13\n\x0b\x66irst_value\x18\x01 \x01(\x05\x12\x12\n\nlast_value\x18\x02 \x01(\x05\",\n\x11GeneratorResponse\x12\x17\n\x0fgenerated_value\x18\x01 \x01(\x05\x32i\n\x10GeneratorService\x12U\n\x08generate\x12\".com.example.grpc.GeneratorRequest\x1a#.com.example.grpc.GeneratorResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GeneratorService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATORREQUEST']._serialized_start=44
  _globals['_GENERATORREQUEST']._serialized_end=103
  _globals['_GENERATORRESPONSE']._serialized_start=105
  _globals['_GENERATORRESPONSE']._serialized_end=149
  _globals['_GENERATORSERVICE']._serialized_start=151
  _globals['_GENERATORSERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
